application: djpotatoblog
version: 8
runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on

libraries:
- name: django
  version: "1.4"

inbound_services:
- warmup

handlers:

- url: /assets
  static_dir: blog/assets
  expiration: '1m'

- url: /favicon.png
  static_files: favicon.png
  upload: favicon.png

- url: /appengine_sessions/clean-up/
  script: main.app
  login: admin

- url: /.*
  script: main.app

skip_files:
- ^(.*/)?app.yaml
- ^(.*/)?app.yml
- ^(.*/)?index.yaml
- ^(.*/)?index.yml
- ^(.*/)?.*\.py[co]
- ^(.*/)?\..*
- tmp
